[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "check-json"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "check-yaml"

[[repos.hooks]]
id = "check-xml"

[[repos.hooks]]
id = "mixed-line-ending"

[[repos.hooks]]
id = "detect-private-key"

[[repos]]
repo = "local"

[[repos.hooks]]
id = "dotnet-format"
name = "dotnet format"
entry = "dotnet"
args = ["format", "src/shmoxy.api/shmoxy.api.csproj", "src/shmoxy/shmoxy.csproj", "src/tests/shmoxy.api.tests/shmoxy.api.tests.csproj"]
language = "system"
files = "\\.cs$"
pass_filenames = false
