#!/bin/bash
# new-pr.sh - Initialize a new PR branch in a separate worktree with documentation tracking
# Usage: ./scripts/new-pr.sh <pr-name> "<description>"

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel)"
WORKTREES_DIR="$REPO_ROOT/../shmoxy-worktrees"
DOCS_PRS_DIR="$WORKTREES_DIR/$SANITIZED_NAME/docs/prs"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Validate arguments
if [ $# -lt 1 ]; then
    log_error "Usage: $0 <pr-name> [<description>]"
    exit 1
fi

PR_NAME="$1"
DESCRIPTION="${2:-}"

# Sanitize PR name for use in branch and worktree names
SANITIZED_NAME=$(echo "$PR_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g')

DOCS_PRS_DIR="$WORKTREES_DIR/$SANITIZED_NAME/docs/prs"

if [ -z "$SANITIZED_NAME" ]; then
    log_error "PR name cannot be empty after sanitization"
    exit 1
fi

BRANCH_NAME="pr/$SANITIZED_NAME"
WORKTREE_PATH="$WORKTREES_DIR/$SANITIZED_NAME"
TIMESTAMP=$(date '+%Y-%m-%d-%H%M')
DOC_FILE="$DOCS_PRS_DIR/${TIMESTAMP}-${SANITIZED_NAME}.md"

# Check if worktree already exists for this PR
if [ -d "$WORKTREE_PATH/.git" ]; then
    log_error "A worktree already exists at $WORKTREE_PATH"
    log_error "Please remove it first or use a different PR name"
    exit 1
fi

log_info "Creating new PR: $PR_NAME"
log_info "Branch: $BRANCH_NAME"
log_info "Worktree: $WORKTREE_PATH"
log_info "Documentation: $DOC_FILE"

# Create worktree with associated branch
git worktree add -b "$BRANCH_NAME" "$WORKTREE_PATH"

log_info "Worktree created successfully at: $WORKTREE_PATH"
log_info "Switched to branch: $BRANCH_NAME"

# Create PR documentation template
cat > "$DOC_FILE" << EOF
# PR: $PR_NAME

**Created:** $(date '+%Y-%m-%d %H:%M:%S')
**Branch:** $BRANCH_NAME
**Worktree Location:** $WORKTREE_PATH

## Description

${DESCRIPTION:-No description provided}

## Notes

Add any relevant notes, decisions, or context here.

---
*This document was auto-generated by scripts/new-pr.sh*
EOF

log_info "PR documentation created at: $DOC_FILE"
echo ""
log_info "To view the documentation:"
echo "  cat $DOC_FILE"
echo ""
log_info "To make changes in this worktree, navigate to:"
echo "  cd $WORKTREE_PATH"
echo ""
log_info "When done, you can merge and clean up with:"
echo "  git -C $WORKTREE_PATH push origin $BRANCH_NAME"
echo "  # Then create PR on your Git hosting platform"
echo "  # After merging: ./scripts/cleanup-pr.sh $SANITIZED_NAME"
